version: "3.8"

services:
  api-gateway:
    build:
      context: /api-gateway
      dockerfile: Dockerfile
    image: promo-it/api-gateway
    container_name: api-gateway_container
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - consultations-service
      - keycloak
    environment:
      SERVER_PORT: 80
      SPRING_CLOUD_GATEWAY_MVC_ROUTES[0]_ID: consultations-service
      SPRING_CLOUD_GATEWAY_MVC_ROUTES[0]_URI: http://consultations-service
      SPRING_CLOUD_GATEWAY_MVC_ROUTES[0]_PREDICATES[0]: Path= /consultations-service/**
      SPRING_CLOUD_GATEWAY_MVC_ROUTES[0]_FILTERS[0]: StripPrefix=1
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8080/realms/PromoIT

  consultations-service:
    build:
      context: /consultations-service
      dockerfile: Dockerfile
    image: promo-it/consultations-service
    container_name: consultations-service_container
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      SERVER_PORT: 80
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8080/realms/PromoIT
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/consultations_db
      SPRING_DATASOURCE_USERNAME: consultations_db_user
      SPRING_DATASOURCE_PASSWORD: consultations_db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_OPEN-IN-VIEW: false
    depends_on:
      - db
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak_container
    restart: unless-stopped
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: keycloak_user
      KEYCLOAK_ADMIN_PASSWORD: keycloak_pass
      KC_HOSTNAME: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/keycloak_db
      KC_DB_USERNAME: keycloak_db_user
      KC_DB_PASSWORD: keycloak_db_password
    ports:
      - "8080:8080"
    depends_on:
      - db

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin_user@foo.bar
      PGADMIN_DEFAULT_PASSWORD: pgadmin_pass
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8082:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    container_name: db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_MULTIPLE_DATABASES: keycloak_db:keycloak_db_user:keycloak_db_password,consultations_db:consultations_db_user:consultations_db_password
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local
